use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct ResourcesRoot {
    #[serde(rename = "Resources")]
    pub resources: Resources,
}

impl Default for ResourcesRoot {
    fn default() -> Self {
        Self {
            resources: Resources::default(),
        }
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Resources {
    pub account_page: String,
    pub account_page_rakuten: String,
    pub add_entitlement: String,
    pub affiliaterequest: String,
    pub audiobook_subscription_orange_deal_inclusion_url: String,
    pub authorproduct_recommendations: String,
    pub autocomplete: String,
    pub blackstone_header: ResourcesHeader,
    pub book: String,
    pub book_detail_page: String,
    pub book_detail_page_rakuten: String,
    pub book_landing_page: String,
    pub book_subscription: String,
    pub categories: String,
    pub categories_page: String,
    pub category: String,
    pub category_featured_lists: String,
    pub category_products: String,
    pub checkout_borrowed_book: String,
    pub configuration_data: String,
    pub content_access_book: String,
    pub customer_care_live_chat: String,
    pub daily_deal: String,
    pub deals: String,
    pub delete_entitlement: String,
    pub delete_tag: String,
    pub delete_tag_items: String,
    pub device_auth: String,
    pub device_refresh: String,
    pub dictionary_host: String,
    pub discovery_host: String,
    pub eula_page: String,
    pub exchange_auth: String,
    pub external_book: String,
    pub facebook_sso_page: String,
    pub featured_list: String,
    pub featured_lists: String,
    pub free_books_page: LocalizedPages,
    pub fte_feedback: String,
    pub get_tests_request: String,
    pub giftcard_epd_redeem_url: String,
    pub giftcard_redeem_url: String,
    pub help_page: String,
    pub kobo_audiobooks_enabled: String,
    pub kobo_audiobooks_orange_deal_enabled: String,
    pub kobo_audiobooks_subscriptions_enabled: String,
    pub kobo_nativeborrow_enabled: String,
    pub kobo_onestorelibrary_enabled: String,
    pub kobo_redeem_enabled: String,
    pub kobo_shelfie_enabled: String,
    pub kobo_subscriptions_enabled: String,
    pub kobo_superpoints_enabled: String,
    pub kobo_wishlist_enabled: String,
    pub library_book: String,
    pub library_items: String,
    pub library_metadata: String,
    pub library_prices: String,
    pub library_stack: String,
    pub library_sync: String,
    pub love_dashboard_page: String,
    pub love_points_redemption_page: String,
    pub magazine_landing_page: String,
    pub notifications_registration_issue: String,
    pub oauth_host: String,
    pub overdrive_account: String,
    pub overdrive_library: String,
    pub overdrive_library_finder_host: String,
    pub overdrive_thunder_host: String,
    pub password_retrieval_page: String,
    pub post_analytics_event: String,
    pub privacy_page: String,
    pub product_nextread: String,
    pub product_prices: String,
    pub product_recommendations: String,
    pub product_reviews: String,
    pub products: String,
    pub provider_external_sign_in_page: String,
    pub purchase_buy: String,
    pub purchase_buy_templated: String,
    pub quickbuy_checkout: String,
    pub quickbuy_create: String,
    pub rating: String,
    pub reading_state: String,
    pub redeem_interstitial_page: String,
    pub registration_page: String,
    pub related_items: String,
    pub remaining_book_series: String,
    pub rename_tag: String,
    pub review: String,
    pub review_sentiment: String,
    pub shelfie_recommendations: String,
    pub sign_in_page: String,
    pub social_authorization_host: String,
    pub social_host: String,
    #[serde(rename = "stacks_host_productId")]
    pub stacks_host_product_id: String,
    pub store_home: String,
    pub store_host: String,
    pub store_newreleases: String,
    pub store_search: String,
    pub store_top50: String,
    pub tag_items: String,
    pub tags: String,
    pub taste_profile: String,
    pub update_accessibility_to_preview: String,
    pub use_one_store: String,
    pub user_loyalty_benefits: String,
    pub user_platform: String,
    pub user_profile: String,
    pub user_ratings: String,
    pub user_recommendations: String,
    pub user_reviews: String,
    pub user_wishlist: String,
    pub userguide_host: String,
    pub wishlist_page: String,
}

impl Default for Resources {
    fn default() -> Self {
        Self {
            account_page: "https://secure.kobobooks.com/profile".to_string(),
            account_page_rakuten: "https://my.rakuten.co.jp/".to_string(),
            add_entitlement: "https://storeapi.kobo.com/v1/library/{RevisionIds}".to_string(),
            affiliaterequest: "https://storeapi.kobo.com/v1/affiliate".to_string(),
            audiobook_subscription_orange_deal_inclusion_url: "https://authorize.kobo.com/inclusion".to_string(),
            authorproduct_recommendations: "https://storeapi.kobo.com/v1/products/books/authors/recommendations".to_string(),
            autocomplete: "https://storeapi.kobo.com/v1/products/autocomplete".to_string(),
            blackstone_header: ResourcesHeader::default(),
            book: "https://storeapi.kobo.com/v1/products/books/{ProductId}".to_string(),
            book_detail_page: "https://store.kobobooks.com/{culture}/ebook/{slug}".to_string(),
            book_detail_page_rakuten: "https://books.rakuten.co.jp/rk/{crossrevisionid}".to_string(),
            book_landing_page: "https://store.kobobooks.com/ebooks".to_string(),
            book_subscription: "https://storeapi.kobo.com/v1/products/books/subscriptions".to_string(),
            categories: "https://storeapi.kobo.com/v1/categories".to_string(),
            categories_page: "https://store.kobobooks.com/ebooks/categories".to_string(),
            category: "https://storeapi.kobo.com/v1/categories/{CategoryId}".to_string(),
            category_featured_lists: "https://storeapi.kobo.com/v1/categories/{CategoryId}/featured".to_string(),
            category_products: "https://storeapi.kobo.com/v1/categories/{CategoryId}/products".to_string(),
            checkout_borrowed_book: "https://storeapi.kobo.com/v1/library/borrow".to_string(),
            configuration_data: "https://storeapi.kobo.com/v1/configuration".to_string(),
            content_access_book: "https://storeapi.kobo.com/v1/products/books/{ProductId}/access".to_string(),
            customer_care_live_chat: "https://v2.zopim.com/widget/livechat.html?key=Y6gwUmnu4OATxN3Tli4Av9bYN319BTdO".to_string(),
            daily_deal: "https://storeapi.kobo.com/v1/products/dailydeal".to_string(),
            deals: "https://storeapi.kobo.com/v1/deals".to_string(),
            delete_entitlement: "https://storeapi.kobo.com/v1/library/{Ids}".to_string(),
            delete_tag: "https://storeapi.kobo.com/v1/library/tags/{TagId}".to_string(),
            delete_tag_items: "https://storeapi.kobo.com/v1/library/tags/{TagId}/items/delete".to_string(),
            device_auth: "https://storeapi.kobo.com/v1/auth/device".to_string(),
            device_refresh: "https://storeapi.kobo.com/v1/auth/refresh".to_string(),
            dictionary_host: "https://kbdownload1-a.akamaihd.net".to_string(),
            discovery_host: "https://discovery.kobobooks.com".to_string(),
            eula_page: "https://www.kobo.com/termsofuse?style=onestore".to_string(),
            exchange_auth: "https://storeapi.kobo.com/v1/auth/exchange".to_string(),
            external_book: "https://storeapi.kobo.com/v1/products/books/external/{Ids}".to_string(),
            facebook_sso_page: "https://authorize.kobo.com/signin/provider/Facebook/login?returnUrl=http://store.kobobooks.com/".to_string(),
            featured_list: "https://storeapi.kobo.com/v1/products/featured/{FeaturedListId}".to_string(),
            featured_lists: "https://storeapi.kobo.com/v1/products/featured".to_string(),
            free_books_page: LocalizedPages::default(),
            fte_feedback: "https://storeapi.kobo.com/v1/products/ftefeedback".to_string(),
            get_tests_request: "https://storeapi.kobo.com/v1/analytics/gettests".to_string(),
            giftcard_epd_redeem_url: "https://www.kobo.com/{storefront}/{language}/redeem-ereader".to_string(),
            giftcard_redeem_url: "https://www.kobo.com/{storefront}/{language}/redeem".to_string(),
            help_page: "https://www.kobo.com/help".to_string(),
            kobo_audiobooks_enabled: "False".to_string(),
            kobo_audiobooks_orange_deal_enabled: "False".to_string(),
            kobo_audiobooks_subscriptions_enabled: "False".to_string(),
            kobo_nativeborrow_enabled: "True".to_string(),
            kobo_onestorelibrary_enabled: "False".to_string(),
            kobo_redeem_enabled: "True".to_string(),
            kobo_shelfie_enabled: "False".to_string(),
            kobo_subscriptions_enabled: "False".to_string(),
            kobo_superpoints_enabled: "False".to_string(),
            kobo_wishlist_enabled: "True".to_string(),
            library_book: "https://storeapi.kobo.com/v1/user/library/books/{LibraryItemId}".to_string(),
            library_items: "https://storeapi.kobo.com/v1/user/library".to_string(),
            library_metadata: "https://storeapi.kobo.com/v1/library/{Ids}/metadata".to_string(),
            library_prices: "https://storeapi.kobo.com/v1/user/library/previews/prices".to_string(),
            library_stack: "https://storeapi.kobo.com/v1/user/library/stacks/{LibraryItemId}".to_string(),
            library_sync: "https://storeapi.kobo.com/v1/library/sync".to_string(),
            love_dashboard_page: "https://store.kobobooks.com/{culture}/kobosuperpoints".to_string(),
            love_points_redemption_page: "https://store.kobobooks.com/{culture}/KoboSuperPointsRedemption?productId={ProductId}".to_string(),
            magazine_landing_page: "https://store.kobobooks.com/emagazines".to_string(),
            notifications_registration_issue: "https://storeapi.kobo.com/v1/notifications/registration".to_string(),
            oauth_host: "https://oauth.kobo.com".to_string(),
            overdrive_account: "https://auth.overdrive.com/account".to_string(),
            overdrive_library: "https://{libraryKey}.auth.overdrive.com/library".to_string(),
            overdrive_library_finder_host: "https://libraryfinder.api.overdrive.com".to_string(),
            overdrive_thunder_host: "https://thunder.api.overdrive.com".to_string(),
            password_retrieval_page: "https://www.kobobooks.com/passwordretrieval.html".to_string(),
            post_analytics_event: "https://storeapi.kobo.com/v1/analytics/event".to_string(),
            privacy_page: "https://www.kobo.com/privacypolicy?style=onestore".to_string(),
            product_nextread: "https://storeapi.kobo.com/v1/products/{ProductIds}/nextread".to_string(),
            product_prices: "https://storeapi.kobo.com/v1/products/{ProductIds}/prices".to_string(),
            product_recommendations: "https://storeapi.kobo.com/v1/products/{ProductId}/recommendations".to_string(),
            product_reviews: "https://storeapi.kobo.com/v1/products/{ProductIds}/reviews".to_string(),
            products: "https://storeapi.kobo.com/v1/products".to_string(),
            provider_external_sign_in_page: "https://authorize.kobo.com/ExternalSignIn/{providerName}?returnUrl=http://store.kobobooks.com/".to_string(),
            purchase_buy: "https://www.kobo.com/checkout/createpurchase/".to_string(),
            purchase_buy_templated: "https://www.kobo.com/{culture}/checkout/createpurchase/{ProductId}".to_string(),
            quickbuy_checkout: "https://storeapi.kobo.com/v1/store/quickbuy/{PurchaseId}/checkout".to_string(),
            quickbuy_create: "https://storeapi.kobo.com/v1/store/quickbuy/purchase".to_string(),
            rating: "https://storeapi.kobo.com/v1/products/{ProductId}/rating/{Rating}".to_string(),
            reading_state: "https://storeapi.kobo.com/v1/library/{Ids}/state".to_string(),
            redeem_interstitial_page: "https://store.kobobooks.com".to_string(),
            registration_page: "https://authorize.kobo.com/signup?returnUrl=http://store.kobobooks.com/".to_string(),
            related_items: "https://storeapi.kobo.com/v1/products/{Id}/related".to_string(),
            remaining_book_series: "https://storeapi.kobo.com/v1/products/books/series/{SeriesId}".to_string(),
            rename_tag: "https://storeapi.kobo.com/v1/library/tags/{TagId}".to_string(),
            review: "https://storeapi.kobo.com/v1/products/reviews/{ReviewId}".to_string(),
            review_sentiment: "https://storeapi.kobo.com/v1/products/reviews/{ReviewId}/sentiment/{Sentiment}".to_string(),
            shelfie_recommendations: "https://storeapi.kobo.com/v1/user/recommendations/shelfie".to_string(),
            sign_in_page: "https://authorize.kobo.com/signin?returnUrl=http://store.kobobooks.com/".to_string(),
            social_authorization_host: "https://social.kobobooks.com:8443".to_string(),
            social_host: "https://social.kobobooks.com".to_string(),
            stacks_host_product_id: "https://store.kobobooks.com/collections/byproductid/".to_string(),
            store_home: "www.kobo.com/{region}/{language}".to_string(),
            store_host: "store.kobobooks.com".to_string(),
            store_newreleases: "https://store.kobobooks.com/{culture}/List/new-releases/961XUjtsU0qxkFItWOutGA".to_string(),
            store_search: "https://store.kobobooks.com/{culture}/Search?Query={query}".to_string(),
            store_top50: "https://store.kobobooks.com/{culture}/ebooks/Top".to_string(),
            tag_items: "https://storeapi.kobo.com/v1/library/tags/{TagId}/Items".to_string(),
            tags: "https://storeapi.kobo.com/v1/library/tags".to_string(),
            taste_profile: "https://storeapi.kobo.com/v1/products/tasteprofile".to_string(),
            update_accessibility_to_preview: "https://storeapi.kobo.com/v1/library/{EntitlementIds}/preview".to_string(),
            use_one_store: "False".to_string(),
            user_loyalty_benefits: "https://storeapi.kobo.com/v1/user/loyalty/benefits".to_string(),
            user_platform: "https://storeapi.kobo.com/v1/user/platform".to_string(),
            user_profile: "https://storeapi.kobo.com/v1/user/profile".to_string(),
            user_ratings: "https://storeapi.kobo.com/v1/user/ratings".to_string(),
            user_recommendations: "https://storeapi.kobo.com/v1/user/recommendations".to_string(),
            user_reviews: "https://storeapi.kobo.com/v1/user/reviews".to_string(),
            user_wishlist: "https://storeapi.kobo.com/v1/user/wishlist".to_string(),
            userguide_host: "https://kbdownload1-a.akamaihd.net".to_string(),
            wishlist_page: "https://store.kobobooks.com/{region}/{language}/account/wishlist".to_string(),
        }
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ResourcesHeader {
    pub key: String,
    pub value: String,
}

impl Default for ResourcesHeader {
    fn default() -> Self {
        Self {
            key: "x-amz-request-payer".to_string(),
            value: "requester".to_string(),
        }
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub struct LocalizedPages {
    #[serde(rename = "EN")]
    pub en: String,
    #[serde(rename = "FR")]
    pub fr: String,
    #[serde(rename = "IT")]
    pub it: String,
    #[serde(rename = "NL")]
    pub nl: String,
    #[serde(rename = "PT")]
    pub pt: String,
}

impl Default for LocalizedPages {
    fn default() -> Self {
        Self {
            en: "https://www.kobo.com/{region}/{language}/p/free-ebooks".to_string(),
            fr: "https://www.kobo.com/{region}/{language}/p/livres-gratuits".to_string(),
            it: "https://www.kobo.com/{region}/{language}/p/libri-gratuiti".to_string(),
            nl: "https://www.kobo.com/{region}/{language}/List/bekijk-het-overzicht-van-gratis-ebooks/QpkkVWnUw8sxmgjSlCbJRg".to_string(),
            pt: "https://www.kobo.com/{region}/{language}/p/livros-gratis".to_string(),
        }
    }
}
